name: GitBot Daily Commits

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight UTC

jobs:
  run-gitbot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Run GitBot
      run: |
        python gitbot.py
